name: Test Whitespace and line endings

on: [pull_request]

jobs:
  eclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.5.1
      - uses: actions/checkout@v3.0.2
        with:
          node-version: '12.x'
      - run: npm i -g eclint
      - run: eclint check
